name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - uses: szepeviktor/phive@v1
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"

      - run: 'yes 2>/dev/null | "${{ github.workspace }}/tools/phive" --home "${{ runner.temp }}/.phive" install --trust-gpg-keys 2A8299CE842DD38C'

      - run: tools/phpunit
